### ISSUE TITLE
Duplicate code, consider revising

### ISSUE THREAD

**Issue by sdace** [Phoenix1128/BattleBot#15]
https://github.com/Phoenix1128/BattleBot/blob/0e8036a213d047f0370e6fa6fd571998215a233a/commands/factions/1ups.js#L26

There should be no references to 'mario' or 'luigi' in the bot's code. Ideally, more than 2 factions should be supported, but for now I would work on refactoring this code so you're not repeating the same blocks of code twice when you could just be passing in parameters to a single function.

**Comment by sdace** [comment]
Any references to strings, if absolutely necessary, should also be defined as constants in some central location so they can be changed throughout the code.

**Comment by pdinsdale** [comment]
Yeah this is something I’ve also fixed in the Development branch just not master yet.

**Comment by pdinsdale** [comment]
Fixed with v1.2.0!
