### ISSUE TITLE
Current year is hard coded

### ISSUE THREAD

**Issue by sdace** [Phoenix1128/BattleBot#16]
https://github.com/Phoenix1128/BattleBot/blob/0e8036a213d047f0370e6fa6fd571998215a233a/commands/factions/results.js#L12

This should definitely not be hard-coded. Please use the Date class to check if the queried year is greater than the current, then same for the month.

**Comment by pdinsdale** [comment]
Yes agreed. Also gonna update this with the results restructuring.

**Comment by pdinsdale** [comment]
Actually completely got rid of this in v1.2.1 cause it was kinda clogging up the code and wasn't really necessary
