### ISSUE TITLE
Make faction battle queries data driven

### ISSUE THREAD

**Issue by sdace** [Phoenix1128/BattleBot#17]
https://github.com/Phoenix1128/BattleBot/blob/0e8036a213d047f0370e6fa6fd571998215a233a/commands/factions/results.js#L29

This really needs to be data driven. An object which maps years to months, and months to faction battle data would work.

**Comment by sdace** [comment]
This would also solve the problem with how 2019 is treated as a special case, as can be seen here https://github.com/Phoenix1128/BattleBot/blob/0e8036a213d047f0370e6fa6fd571998215a233a/commands/factions/results.js#L150

**Comment by pdinsdale** [comment]
Yes this is on my To Do list with json or enmap integration

**Comment by pdinsdale** [comment]
Fixed in v1.2.1!
