### ISSUE TITLE
Reducing 8-ball complexity

### ISSUE THREAD

**Issue by sdace** [Phoenix1128/BattleBot#18]
https://github.com/Phoenix1128/BattleBot/blob/0e8036a213d047f0370e6fa6fd571998215a233a/commands/fun/8ball.js#L10

**suggestion**
Strings should just be in a numbered array, and you use the random number as an index into it. No need for a long switch case.

**Comment by pdinsdale** [comment]
That’s true. I’ll get to work on that

**Comment by pdinsdale** [comment]
Fixed in v1.2.1!
