### ISSUE TITLE
Emojis?

### ISSUE THREAD

**Issue by sdace** [Phoenix1128/BattleBot#19]
https://github.com/Phoenix1128/BattleBot/blob/0e8036a213d047f0370e6fa6fd571998215a233a/commands/fun/slots.js#L6

I really hate seeing emojis inside of source code. My intuition is telling me there's a more kosher way to do this.

**Comment by pdinsdale** [comment]
There probably is. I could possibly move these to a json file.

**Comment by pdinsdale** [comment]
Fixed in v1.2.1!
