### ISSUE TITLE
Arbitrary data in source code

### ISSUE THREAD

**Issue by sdace** [Phoenix1128/BattleBot#20]
https://github.com/Phoenix1128/BattleBot/blob/0e8036a213d047f0370e6fa6fd571998215a233a/bot.js#L118

I don't mind this blacklist existing, but I would rather they be parsed from a text file or something like that, and possibly also excluded from the git repo but that's up to you. If you embed this in the source code, you have to restart the bot every time you update it, or do something similarly nasty. If you update it in a txt file or json, all you need to do is run a command to update the list with the new contents of the file.

**Comment by pdinsdale** [comment]
Yes I’ve currently fixed that to use Enmap arrays so it’s not hard coded in any way. Currently everything on master is extremely outdated as I’ve been pushing to the Development branch in preparation for v2.0.0 but I think I’ll release v1.2.0 with some of the older changes that should have been there a long time ago

**Comment by pdinsdale** [comment]
Fixed in v1.2.0!
